#!/bin/sh

set -e

# change this to the location where you put the .dl file:
FIRMWARE="/usr/lib/sihp1018.dl"

DEVICE=/dev/usb/lp0
LOGFILE=/var/log/hp

if [ "$PRODUCT" = "3f0/4117/100" -a "$ACTION" = "add" ]; then
	for i in $(seq 30); do
		if [ -c $DEVICE ]; then
			echo "$(date) : Sending firmware to printer…" > $LOGFILE
			cat $FIRMWARE > $DEVICE
			echo "$(date) : done." » $LOGFILE
			exit
		fi
		sleep 1
	done
fi
